## Numpy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.21.6


In [3]:
# Creamos un array
arr = np.array([1,2,3,4,5,6,7,8,9])

In [4]:
type(arr)

numpy.ndarray

In [5]:
# Operaciones matemáticas
arr*10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
# Array de mas de una dimensión
arr2d = np.array([[1,2,3], [4,5,6]])

In [7]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

In [9]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
arr3d.ndim

3

In [11]:
# Array de n dimensiones
arr6d = np.array([1,2], ndmin= 6)

In [12]:
arr6d

array([[[[[[1, 2]]]]]])

In [13]:
arr.size

9

In [14]:
arr2d.size

6

In [15]:
arr2d[1,1]

5

In [16]:
arr[2:5]

array([3, 4, 5])

In [17]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[:5]

array([1, 2, 3, 4, 5])

In [19]:
arr2d[0:2, 1:2]

array([[2],
       [5]])

In [20]:
# Comparativa numpy - python list
from datetime import datetime
py_list = [i for i in range(1000000)]
start = datetime.now()
py_list = [i+3 for i in py_list]
end = datetime.now()
print(end - start)

0:00:00.185637


In [21]:
np_array = np.array([i for i in range (1000000)])
start = datetime.now()
np_array += 3
end = datetime.now()
print(end - start)

0:00:00.001876


In [22]:
arr2d.shape
arr3d.shape

(2, 2, 3)

In [23]:
reshapeArr = arr.reshape(3,3)
reshapeArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
reshapeArr2d = arr2d.reshape(-1)#el -1 deja el arreglo en una sola dimesión
reshapeArr2d

array([1, 2, 3, 4, 5, 6])

In [25]:
search = np.where(arr == 5)# Devuelve el índice donde está ubicado el elemento
search

(array([4]),)

In [26]:
arrDes = np.array([58,52,69,87,96,2,2,14,2,3])
np.sort(arrDes) # Ordena los elementos de un array

array([ 2,  2,  2,  3, 14, 52, 58, 69, 87, 96])

In [27]:
filtro = arr > 5
newArr = arr[filtro]
filtro
newArr

array([6, 7, 8, 9])

In [28]:
arange = np.arange(50)
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [29]:
import sys
s = range(1000)
print(s)
print("Tamaño de cada elemento de la lista en bytes: ", sys.getsizeof(s))
print("Tamaño total de la lista en bytes: ", sys.getsizeof(s)*len(s))

range(0, 1000)
Tamaño de cada elemento de la lista en bytes:  48
Tamaño total de la lista en bytes:  48000


In [30]:
nS = np.arange(1000)
print("Tamaño de cada elemento de la lista en bytes: ", nS.itemsize)
print("Tamaño total de la lista en bytes: ", nS.itemsize*nS.size)

Tamaño de cada elemento de la lista en bytes:  8
Tamaño total de la lista en bytes:  8000


In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.linspace(2,20, num=6)#Permite crear un array distribuido uniformemente con un intervalo especificado

array([ 2. ,  5.6,  9.2, 12.8, 16.4, 20. ])

In [34]:
np.linspace(2,20, num=6, endpoint = False)

array([ 2.,  5.,  8., 11., 14., 17.])

In [35]:
randUniform = np.random.rand(20)
randUniform

array([0.12124392, 0.4714846 , 0.75366586, 0.28301106, 0.28852682,
       0.45914621, 0.73004227, 0.77983333, 0.5470837 , 0.26144003,
       0.86491965, 0.30491243, 0.70220628, 0.86306153, 0.74118434,
       0.88827948, 0.73420784, 0.69464474, 0.26043196, 0.09295798])

In [36]:
randNormal = np.random.randn(20)
randNormal

array([-0.32666885,  1.089194  ,  0.14042711, -0.14333422,  1.22072513,
        2.708402  ,  0.69007243,  1.25054295, -0.22461468,  0.25673089,
        0.42056715, -0.74016316,  0.73883103, -1.0653851 ,  1.08991633,
       -0.06940324, -0.30457141,  0.71342106, -1.98228723,  1.16589162])

In [37]:
arr1 = np.arange(1,10)

In [38]:
print(arr1+5)
print(arr1*5)
print(arr1/5)

[ 6  7  8  9 10 11 12 13 14]
[ 5 10 15 20 25 30 35 40 45]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


In [39]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1 * 2
arr3 = np.concatenate((arr1, arr2))
arr3

array([ 1,  2,  3,  4,  5,  2,  4,  6,  8, 10])

In [41]:
arr3a = np.stack((arr1, arr2))
arr3a

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

In [42]:
arr3a.shape

(2, 5)

In [43]:
arrV = np.vstack((arr1, arr2))
arrV

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

In [45]:
arrH = np.hstack((arr1, arr2))
arrH

array([ 1,  2,  3,  4,  5,  2,  4,  6,  8, 10])

In [47]:
np.array_split(arr1, 2)# Divide un array en diferentes arrays

[array([1, 2, 3]), array([4, 5])]

In [48]:
np.array_split(arr2d, 2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [53]:
np.insert(arr, 2, 999)#Añade en un indice en particular

array([  1,   2, 999,   3,   4,   5,   6,   7,   8,   9])

In [54]:
np.append(arr, 999)#Añade al final

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 999])

In [55]:
np.delete(arr, 4)#Elimina el elemento ubicado en el índice indicado

array([1, 2, 3, 4, 6, 7, 8, 9])